version: "3.9"

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy

    command:
      - run
      - /etc/alloy/config.alloy

    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy:ro

    ports:
      - "4318:4318"   #OTLP HTTP
      - "12345:12345" #Alloy UI
    
    depends_on:
      - loki
    
    restart: unless-stopped
  
  loki:
    image: grafana/loki:main-034bb7e
    container_name: loki

    command: -config.file=/etc/loki/config.yaml

    volumes:
      - ./observability/loki/config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"

    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    depends_on:
      - loki

    ports:
      - "8000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana-data:/var/lib/grafana

    restart: unless-stopped

volumes:
  loki-data:
  grafana-data: